backend:
  name: github
  repo: Vaxraa/demo
  branch: main
  
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu"
    folder: "content/menu"
    create: true
    format: "json"
    fields:
      - { label: "Item Name", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }